name: cp949
version: 0.1.0
description: CP949 Encoder/Decoder
environment:
  sdk: ">=1.1.3 <3.0.0"
homepage: https://github.com/jjangga0214/dart-cp949
repository: https://github.com/jjangga0214/dart-cp949
issue_tracker: https://github.com/jjangga0214/dart-cp949/issues
documentation: https://github.com/jjangga0214/dart-cp949
dev_dependencies:
  test: ^1.15.4
